## Tensor Basic


Walk through of a lot of different useful Tensor Operations, where we
go through what I think are four main parts in:

1. Initialization of a Tensor
2. Tensor Mathematical Operations and Comparison
3. Tensor Indexing
4. Tensor Reshaping

But also other things such as setting the device (GPU/CPU) and converting
between different types (int, float etc) and how to convert a tensor to an
numpy array and vice-versa.

---
### 1. Initialization of a Tensor

In [1]:
import torch
import numpy as np

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


In [3]:
# Initial a Tensor in this case of shape 2x3
tensor1 = torch.tensor(
    [[1,2,3],[4,5,6]], dtype=torch.float32, device = device, requires_grad=True
)
print(f"Tensor1: {tensor1}")

print(f"Type of Tensor1: {tensor1.dtype}")

print(f"Device Tensor 1: {tensor1.device}")

print(f"Shape of Tensor 1: {tensor1.shape}")

print(f"Requires of Gradient: {tensor1.requires_grad}")

Tensor1: tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
Type of Tensor1: torch.float32
Device Tensor 1: cuda:0
Shape of Tensor 1: torch.Size([2, 3])
Requires of Gradient: True


In [4]:
# Other Initial method

tensor_empty = torch.empty(size=(3,3)) # Tensor (3,3) with ununtialize data
print(f"Tensor Empty: {tensor_empty}")

tensor_zeros = torch.zeros(size = (3,3)) # Tensor (3,3) with all data = 0
print(f"Tensor Zeros: {tensor_zeros}")

tensor_rand = torch.rand(size=(3,3)) # [0,1)
print(f"Tensor Rand: {tensor_rand}")


tensor_ones = torch.ones(size=(3,3)) # Tensor (3,3) with values of 1
print(f"Tensor Ones: {tensor_ones}")

tensor_eye = torch.eye(5,5)
print(f"Tensor Eye: {tensor_eye}")

tensor_arange = torch.arange(start=0, end=5, step=1)
print(f"Tensor Arange: {tensor_arange}")

tensor_linspace = torch.linspace(start=0.1, end=1, steps=10)
print(f"Tensor Linspace: {tensor_linspace}")

tensor_normal_distribute = torch.empty(size = (1,5)).normal_(mean=0, std=1)
print(f"Tensor Normal Distribute: {tensor_normal_distribute}")

tensor_uniform_distribute = torch.empty(size=(1,5)).uniform_(0,1)
print(f"Tensor Uniform Distribute: {tensor_uniform_distribute}")

tensor_diag = torch.diag(torch.ones(4)) # Diag matrix (4,4)
print(f"Tensor Diag: {tensor_diag}")





Tensor Empty: tensor([[2.1536e+21, 4.5839e-41, 2.1536e+21],
        [4.5839e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
Tensor Zeros: tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Tensor Rand: tensor([[0.8432, 0.9407, 0.2963],
        [0.9994, 0.4091, 0.5442],
        [0.6775, 0.2997, 0.1824]])
Tensor Ones: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Tensor Eye: tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Tensor Arange: tensor([0, 1, 2, 3, 4])
Tensor Linspace: tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
Tensor Normal Distribute: tensor([[ 2.4313, -0.2577, -0.2841, -0.2073, -1.9309]])
Tensor Uniform Distribute: tensor([[0.1507, 0.6110, 0.1227, 0.0395, 0.2416]])
Tensor Diag: tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
   

In [5]:
# How to make initialized tensors to other types (int, float, double)
# These will work even if you're on CPU or CUDA!

tensor = torch.arange(4) # int32
print(tensor)

print(f"Tensor convert to Bool: {tensor.bool()}")
print(f"Tensor convert to int16: {tensor.short()}")
print(f"Tensor convert to int64: {tensor.long()}") # Converted to int64 (This one is very important, used super often)

print(f"Tensor convert to float16: {tensor.half()}")
print(f"Tensor convert to float32: {tensor.float()}")
print(f"Tensor convert to float64: {tensor.double()}")

# Tensor to numpy
numpy_tensor = tensor.numpy()
print(f"Tensor to numpy: {numpy_tensor}")

# Numpy to tensor
numpy_array = np.array([1,2,3,4])
tensor_from_numpy = torch.from_numpy(numpy_array)
print(f"Numpy to tensor: {tensor_from_numpy}")


tensor([0, 1, 2, 3])
Tensor convert to Bool: tensor([False,  True,  True,  True])
Tensor convert to int16: tensor([0, 1, 2, 3], dtype=torch.int16)
Tensor convert to int64: tensor([0, 1, 2, 3])
Tensor convert to float16: tensor([0., 1., 2., 3.], dtype=torch.float16)
Tensor convert to float32: tensor([0., 1., 2., 3.])
Tensor convert to float64: tensor([0., 1., 2., 3.], dtype=torch.float64)
Tensor to numpy: [0 1 2 3]
Numpy to tensor: tensor([1, 2, 3, 4])


---
### 2. Tensor Math & Comparison Operations

In [6]:
x = torch.tensor([1,2,3,4,5])
y = torch.tensor([6,7,8,9,10])

# ----------Addition---------------
z1 = torch.empty(5)
torch.add(x,y,out=z1) # This is one way

z2 = torch.add(x,y) # This is another way

z3 = x+y # simple way :-)
print(f"Way1: {z1}")
print(f"Way2: {z2}")
print(f"Best way: {z3}")

# --------- Subtraction -------------
z_subtract = x - y
print("Subtraction: ", z_subtract)


# Division (A bit clunky)
z_division = torch.true_divide(y,x)
print(f"Devision: {z_division}")

# --------- Inplace Operations ---------
t = torch.zeros(5)
t.add_(x)
print(t)
t += x # != t = t + x because t=t+x add memory
print(t)

# ---------- Exponentiation ---------------
ex1 = x.pow(2)
print(ex1)

ex2 = x**2
print(ex2)

# -----------Simple Comparison ------------
z_compare = x > 0
print(z_compare)

z_compare_another = x < 0
print(z_compare_another)


Way1: tensor([ 7.,  9., 11., 13., 15.])
Way2: tensor([ 7,  9, 11, 13, 15])
Best way: tensor([ 7,  9, 11, 13, 15])
Subtraction:  tensor([-5, -5, -5, -5, -5])
Devision: tensor([6.0000, 3.5000, 2.6667, 2.2500, 2.0000])
tensor([1., 2., 3., 4., 5.])
tensor([ 2.,  4.,  6.,  8., 10.])
tensor([ 1,  4,  9, 16, 25])
tensor([ 1,  4,  9, 16, 25])
tensor([True, True, True, True, True])
tensor([False, False, False, False, False])


In [7]:
# ----------- Matrix Multiplication -------
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))

x3 = torch.mm(x1,x2) # Matrix multiplication of x1 and x2, out shape: 2x3
x4 = x1.mm(x2) # Another way matrix multiplication

print(x3)
print(x4)

# Matrix exponentiation
matrix_exp1 = torch.tensor([[1,2],[4,5]])
matrix_exp2 = torch.tensor([[2,3],[3,4]])

print(f"Matrix pow 2: {matrix_exp1.matrix_power(2)}")
print(f"Same pow 2: {matrix_exp1.mm(matrix_exp1)}")  # is same as matrix_exp (mm) matrix_exp (mm) matrix_exp

# But matrix_exp1 ** matrix_exp2 is correct for any matrix have same shape
mt_exp1 = torch.tensor([[1,2,3],[4,5,6]])
mt_exp2 = torch.tensor([[2,2,2], [2,2,2]])
print(f"Matrix exp1 ** matrix exp2: {mt_exp1 ** mt_exp2}")

# -------------- Element wise Multiplication---------------
zz = x * y
print(zz) # [1*6 ,2*7 , ...,5*10]

zz2 = matrix_exp1 * matrix_exp2
print(zz2)


# Dot product
dot_1 = torch.dot(x,y)
print(dot_1) # 1*6 + ....+ 5*20

try:
  dot_2 = torch.dot(matrix_exp1, matrix_exp2) # .dot method only use for 1D (not use 2D)
  print(dot_2)
except Exception as e:
  print(e)


  # ----------- Batch Matrix Multiplication ---------------
  batch = 32
  n = 10
  m = 20
  p = 30

  tensor1 = torch.rand((batch, n, m))
  tensor2 = torch.rand((batch, m, p))
  out_bmm = torch.bmm(tensor1, tensor2)
  # print(out_bmm)
  print(out_bmm.shape) # (batch, n, p)

  # ------------- Example of broadcasting -------------
  x1 = torch.tensor([[1,2,3,4,5],[4,5,6,7,8]])
  x2 = torch.ones((1,5))

  z = (x1 - x2)
  print(z) # shape (5,5)

  z = (x1 ** x2)
  print(z)


  # ---------------Other useful tensor operation---------------------

  sum_x = torch.sum(x,dim=0) # result is a tensor
  print(sum_x)

  values, indices = torch.max(x, dim = 0) # tensor
  print(values, indices)

  values ,indices = torch.min(x, dim = 0) # tensor
  print(values, indices)

  abs_x = torch.abs(x) # Return x where abs function applied to every element
  print(abs_x) # tensor

  z = torch.argmax(x, dim = 0) # Gets index of the maximum value - tensor
  print(z)

  z = torch.argmin(x, dim = 0) # Gets index of minimum value - tensor
  print(z)

  mean_x = torch.mean(x.float(), dim = 0)
  print(mean_x)

  z = torch.eq(x,y)
  print(z)

  sorted_y, indices = torch.sort(y, dim = 0, descending = False)
  print(sorted_y, indices)

  # All values < 0 set to 0 and values > 0 unchanged (this is exactly ReLU function)
  # If you want to values over max_val to be clamped, do torch.clamp(x, min=min_val, max=max_val)
  z = torch.clamp(x, min = 3)
  print(z)


  xx = torch.tensor([1, 0, 1, 1, 1], dtype=torch.bool)  # True/False values
  z = torch.any(xx)  # will return True, can also do x.any() instead of torch.any(x)
  print(z)
  z = torch.all(
      xx
  )  # will return False (since not all are True), can also do x.all() instead of torch.all()
  print(z)




tensor([[0.5507, 0.6927, 0.9909],
        [1.0977, 1.0830, 1.7345]])
tensor([[0.5507, 0.6927, 0.9909],
        [1.0977, 1.0830, 1.7345]])
Matrix pow 2: tensor([[ 9, 12],
        [24, 33]])
Same pow 2: tensor([[ 9, 12],
        [24, 33]])
Matrix exp1 ** matrix exp2: tensor([[ 1,  4,  9],
        [16, 25, 36]])
tensor([ 6, 14, 24, 36, 50])
tensor([[ 2,  6],
        [12, 20]])
tensor(130)
1D tensors expected, but got 2D and 2D tensors
torch.Size([32, 10, 30])
tensor([[0., 1., 2., 3., 4.],
        [3., 4., 5., 6., 7.]])
tensor([[1., 2., 3., 4., 5.],
        [4., 5., 6., 7., 8.]])
tensor(15)
tensor(5) tensor(4)
tensor(1) tensor(0)
tensor([1, 2, 3, 4, 5])
tensor(4)
tensor(0)
tensor(3.)
tensor([False, False, False, False, False])
tensor([ 6,  7,  8,  9, 10]) tensor([0, 1, 2, 3, 4])
tensor([3, 3, 3, 4, 5])
tensor(True)
tensor(False)


---
### 3. Tensor Indexing   


In [8]:
batch_size = 10
features = 25
x = torch.rand((batch_size,features))
print(x)

tensor([[0.8297, 0.6948, 0.6875, 0.5439, 0.6012, 0.9086, 0.3685, 0.6243, 0.1366,
         0.5496, 0.1458, 0.6246, 0.9789, 0.4966, 0.4769, 0.5377, 0.6986, 0.6753,
         0.0169, 0.2769, 0.7703, 0.7720, 0.8400, 0.0610, 0.8552],
        [0.2043, 0.8822, 0.2987, 0.1924, 0.7161, 0.0164, 0.0800, 0.8820, 0.8246,
         0.2241, 0.5230, 0.9861, 0.0101, 0.5571, 0.2210, 0.2261, 0.1731, 0.6673,
         0.2633, 0.3287, 0.7680, 0.7554, 0.8302, 0.6332, 0.8193],
        [0.9995, 0.6451, 0.3365, 0.6056, 0.3999, 0.0964, 0.5103, 0.6343, 0.1422,
         0.7203, 0.0690, 0.0313, 0.7197, 0.7252, 0.5297, 0.7772, 0.7394, 0.6076,
         0.7242, 0.2436, 0.8102, 0.4284, 0.1064, 0.2363, 0.7166],
        [0.8981, 0.6963, 0.9331, 0.2700, 0.5930, 0.4046, 0.5875, 0.1083, 0.3337,
         0.3841, 0.2882, 0.2257, 0.8731, 0.2684, 0.7816, 0.8901, 0.9157, 0.7909,
         0.0642, 0.1251, 0.7130, 0.4963, 0.8127, 0.5857, 0.9366],
        [0.3339, 0.7284, 0.4829, 0.0329, 0.2491, 0.9126, 0.6837, 0.8634, 0.4321,
       

In [12]:
# Get first features
print(x[0].shape) # This is same x[0,:]
print(x[0,:])


torch.Size([25])
tensor([0.8297, 0.6948, 0.6875, 0.5439, 0.6012, 0.9086, 0.3685, 0.6243, 0.1366,
        0.5496, 0.1458, 0.6246, 0.9789, 0.4966, 0.4769, 0.5377, 0.6986, 0.6753,
        0.0169, 0.2769, 0.7703, 0.7720, 0.8400, 0.0610, 0.8552])


In [17]:
# Get first features for all example
print(x[:,0])
print(x[:,0].shape)

tensor([0.8297, 0.2043, 0.9995, 0.8981, 0.3339, 0.6276, 0.1109, 0.8092, 0.7492,
        0.5289])
torch.Size([10])


In [16]:
# Access third example in the batch and the first ten features
print(x[2,0:10])
print(x[2,0:10].shape)

tensor([0.9995, 0.6451, 0.3365, 0.6056, 0.3999, 0.0964, 0.5103, 0.6343, 0.1422,
        0.7203])
torch.Size([10])


In [18]:
# Assign certain elements
x[0,0] = 100
print(x[0])

tensor([1.0000e+02, 6.9478e-01, 6.8753e-01, 5.4388e-01, 6.0124e-01, 9.0858e-01,
        3.6848e-01, 6.2432e-01, 1.3661e-01, 5.4963e-01, 1.4577e-01, 6.2456e-01,
        9.7891e-01, 4.9661e-01, 4.7688e-01, 5.3771e-01, 6.9862e-01, 6.7534e-01,
        1.6860e-02, 2.7691e-01, 7.7028e-01, 7.7199e-01, 8.4005e-01, 6.1007e-02,
        8.5518e-01])


In [22]:
# Fancy Indexing
x = torch.arange(10)
indices = [2,5,8]
print(x[indices])

x = torch.rand((3,5))
rows = torch.tensor([1,0])
cols = torch.tensor([4,0])

print(x)
print(x[rows, cols]) # Get the second row fifth column and first row first column

tensor([2, 5, 8])
tensor([[0.2214, 0.2200, 0.1379, 0.7812, 0.2708],
        [0.2632, 0.9251, 0.0706, 0.5818, 0.6310],
        [0.4344, 0.1265, 0.5393, 0.2553, 0.4777]])
tensor([0.6310, 0.2214])


In [25]:
# More advance indexing
x = torch.arange(10)

print(x[(x < 2) | (x > 8)]) # Result 0,1,9
print(x[x.remainder(2) == 0])

tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])


In [29]:
# Useful operations for indexing

# where
print(
    torch.where(x > 5, x, 3*x)
)

# unique
x = torch.tensor([1,1,1,1,2,3,3,3,4])
print(x.unique())

# dimension
print(
    x.ndimension()
)

# numel
x = torch.rand((2,4))
print(
    x.numel()
) # The number of elements in x (in this case it's trivial because it's just a vector)



tensor([ 0,  3,  6,  9, 12, 15,  6,  7,  8,  9])
tensor([1, 2, 3, 4])
1
8


---
### 4. Tensor Reshaping

In [39]:
# Tensor 1D 9 element
x = torch.arange(9)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


In [40]:
# ------------------- VIEW ------------------------------

# view() to (3,3)
print(f"Continues:{x.is_contiguous()}")
x_3x3 = x.view(3,3)
print(x_3x3)

Continues:True
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


-> View() chỉ làm việc với tensor liên tục

In [41]:
# --------------------RESHAPE----------------------
x_3x3 = x.reshape(3,3)
print(x_3x3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


-> reshape() giống view, nhưng nó có thể làm việc với tensor không liên tục nhờ việc copy qua bộ nhớ để nó liên tục

In [43]:
# -----------------TRANSPOSE----------------------
y = x_3x3.t()
print(y.is_contiguous())
print(y)

# Lúc này tensor không liên tục -> dùng view sẽ báo lỗi
try:
  print(y.view(9))
except Exception as e:
  print(e)
# Muốn dùng view phải chuyển nó liên tục trước
print(y.contiguous().view(9))

False
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [53]:
# ---------------- CAT TWO TENSOR-----------------------
x1 = torch.rand((2,5))
x2 = torch.rand((2,5))

# Cat theo chiều ngang - dim = 0 - shape 4x5
print(torch.cat((x1,x2), dim = 0))

# Cat theo chiều dọc - dim = 1 - shape 2x10
print(torch.cat((x1,x2), dim = 1))

tensor([[0.3351, 0.7853, 0.7003, 0.2305, 0.2550],
        [0.0225, 0.4304, 0.5732, 0.4298, 0.7555],
        [0.8798, 0.3105, 0.0714, 0.5414, 0.3200],
        [0.9712, 0.2932, 0.1045, 0.0161, 0.3567]])
tensor([[0.3351, 0.7853, 0.7003, 0.2305, 0.2550, 0.8798, 0.3105, 0.0714, 0.5414,
         0.3200],
        [0.0225, 0.4304, 0.5732, 0.4298, 0.7555, 0.9712, 0.2932, 0.1045, 0.0161,
         0.3567]])


In [54]:
# -------------UNROLL TENSOR TO 1D---------------------
print(f"Contiguous: {x1.is_contiguous()}")
z = x1.view(-1)
print(z)


Contiguous: True
tensor([0.3351, 0.7853, 0.7003, 0.2305, 0.2550, 0.0225, 0.4304, 0.5732, 0.4298,
        0.7555])


> view(-1) chuyển mọi phần tử của tensor thành vector 1 chiều.

In [55]:
# Thay đổi hình dạng giữ nguyên một chiều
batch = 64
x = torch.rand((batch, 2,5))
print(x.shape)
z = x.view((batch, -1))
print(z.shape)

torch.Size([64, 2, 5])
torch.Size([64, 10])


> Tạo tensor 3 chiều: batch=64, mỗi batch có 2x5.
->  view(batch, -1) chuyển mỗi batch thành vector 10 phần tử.

In [61]:

# Hoán cị các chiều của tensor
print(x[0])
z = x.permute(0,2,1)
print(z[0])

tensor([[0.4596, 0.2711, 0.7176, 0.0451, 0.0335],
        [0.3680, 0.0531, 0.4322, 0.6605, 0.2232]])
tensor([[0.4596, 0.3680],
        [0.2711, 0.0531],
        [0.7176, 0.4322],
        [0.0451, 0.6605],
        [0.0335, 0.2232]])


> Đổi vị trí các chiều: từ (batch, 2, 5) thành (batch, 5, 2).

> permute cho phép sắp xếp lại thứ tự các chiều tuỳ ý.

In [64]:
# Cắt tensor thành nhiều phần theo chiều nhất định
print(x.shape)
z = torch.chunk(x, chunks = 2, dim = 1)
print(z[0].shape)
print(z[1].shape)

torch.Size([64, 2, 5])
torch.Size([64, 1, 5])
torch.Size([64, 1, 5])


In [65]:
# Thêm chiều mới unsqueeze
x = torch.arange(10)
print(x.shape)
print(x.unsqueeze(0).shape) # 1 x 10
print(x.unsqueeze(1).shape) # 10 x 1

torch.Size([10])
torch.Size([1, 10])
torch.Size([10, 1])


- unsqueeze(0): Thêm chiều ở đầu, từ [10] thành [1, 10].
- unsqueeze(1): Thêm chiều ở sau, từ [10] thành [10, 1].

In [73]:
# Loại bỏ chiều đơn

x = torch.arange(10).unsqueeze(0).unsqueeze(1)  # Shape: [1, 1, 10]
print(x)
z = x.squeeze(1)  # Trả về [1, 10]
print(z)

tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])


In [74]:
!git clone https://github.com/vdnghia03/Deep-Learning.git

Cloning into 'Deep-Learning'...
remote: Enumerating objects: 86, done.
remote: Counting objects: 100% (86/86), done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 86 (delta 28), reused 3 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (86/86), 3.56 MiB | 9.74 MiB/s, done.
Resolving deltas: 100% (28/28), done.


In [79]:
!find / -name "PT1_Tensor_Basic.ipynb" 2>/dev/null
